/**
 * Writes CONTRACT-GAPS.md — the list of everything this implementation refused
 * to invent.
 *
 * This is the deliverable back to whoever owns the specification: each entry is
 * a concrete artifact that must be authored before the corresponding capability
 * can be built. The same data is served live at GET /internal/contract-gaps.
 *
 * Gaps register themselves as a side effect of module load, so the modules that
 * declare them must be imported here.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Importing for the registerContractGap side effects.
import "../src/core/auth/authorize.js";
import "../src/core/auth/principal.js";
import "../src/core/errors/database.js";
import "../src/core/errors/unregistered.js";
import "../src/core/events/outbox.js";
import "../src/modules/ai/query.routes.js";
import "../src/modules/forests/parcels.routes.js";
import "../src/modules/forests/projects.routes.js";

import { listContractGaps } from "../src/core/spec/contract-gap.js";
import { requirements, specVersion } from "../src/core/spec/registry.js";

const gaps = listContractGaps();

const blockedRequirements = new Map<string, string[]>();
for (const gap of gaps) {
  for (const id of gap.blockedRequirementIds) {
    blockedRequirements.set(id, [...(blockedRequirements.get(id) ?? []), gap.operation]);
  }
}

const lines: string[] = [
  "# Contract gaps",
  "",
  `Specification package version: **${specVersion}**`,
  "",
  "Release 0 is explicitly a foundation package, not the complete production",
  "contract set. DEV-AI-001 forbids coding agents from inventing the missing",
  "contracts, so the implementation refuses the affected operations at runtime",
  "with `SPECIFICATION_CONTRACT_MISSING` (409) instead of guessing.",
  "",
  "Each entry below is a concrete artifact that must be authored and approved",
  "before the corresponding capability can be implemented.",
  "",
  "> Generated by `npm run gaps`. Also served live at `GET /internal/contract-gaps`.",
  "",
  `## ${gaps.length} open gaps`,
  "",
];

for (const gap of gaps) {
  lines.push(`### ${gap.operation}`, "");
  lines.push("Missing artifacts:", "");
  for (const artifact of gap.missingArtifacts) lines.push(`- \`${artifact}\``);
  lines.push("");
  if (gap.blockedRequirementIds.length > 0) {
    const detail = gap.blockedRequirementIds
      .map((id) => `${id} (${requirements.get(id)?.title ?? "unknown requirement"})`)
      .join(", ");
    lines.push(`Blocks: ${detail}`, "");
  }
  if (gap.notes) lines.push(gap.notes, "");
}

lines.push("## Requirements blocked, by id", "");
lines.push("| Requirement | Title | Blocked by |");
lines.push("| --- | --- | --- |");
for (const [id, operations] of [...blockedRequirements.entries()].sort()) {
  const title = requirements.get(id)?.title ?? "—";
  lines.push(`| ${id} | ${title} | ${operations.join("; ")} |`);
}
lines.push("");

const outputPath = resolve(process.cwd(), "CONTRACT-GAPS.md");
writeFileSync(outputPath, lines.join("\n"), "utf8");
console.log(`wrote ${outputPath} (${gaps.length} gaps)`);
